### PR TITLE
Missing sites in manifest

### PR DESCRIPTION
**Pull request by megapro17**

### CODE REVIEW

**Comment by qrlk** [comment]
These sites are not 'missing' like I forgot to include them in the manifest.

Despite the fact that they share the same user base and the roulette script is the same, the frontend of the sites is different in detail and I have no way to easily adapt and test it for all 40+ instances, so it's limited to videochatru.com for now.

Support for all 'access points' will take a lot of resources, which is unwise to spend when all the functionality is available on videochatru.com.

I don't see any reason why I should accept this PR, but thanks for the attention to the project.

**Comment by megapro17** [comment]
Some sites are perfectly working like ome.tv because they're very similar. Add at least a few of these

**Comment by qrlk** [comment]
For a quick look, ome.tv doesn't have a 'header' element which is used in some extension's functionality so the extension's content script will crash depending on its settings.

What would happen if a user is banned? Is 'are you there please make yourself visible' window the same? How to detect and adapt to possible changes in the future? 

Maybe in the future (if this extension becomes popular) I'll also try to test and add full ome.tv support, but right now I'm too busy with other projects. There are a lot of poorly hardcoded things for videochatru.com that I'm not sure will work the same way for ome.tv & others

**Comment by qrlk** [comment]
ome.tv support added in v1.4.0

**Pull request closed without merging**
